"""add_video_engine_columns

Revision ID: 55183369d169
Revises: b6211eb2aedc
Create Date: 2026-05-26 03:19:34.862422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55183369d169'
down_revision: Union[str, None] = 'b6211eb2aedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_segments', sa.Column('keyword', sa.String(length=255), nullable=True))
    op.add_column('video_jobs', sa.Column('full_script', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'full_script')
    op.drop_column('script_segments', 'keyword')
    # ### end Alembic commands ###