"""add_tiktok_research_tables

Revision ID: b6211eb2aedc
Revises: 690586181b46
Create Date: 2026-05-26 02:36:56.684560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6211eb2aedc'
down_revision: Union[str, None] = '690586181b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_research_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiktok_trend_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('views', sa.String(length=50), nullable=True),
    sa.Column('likes', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=50), nullable=True),
    sa.Column('engagement', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=100), nullable=True),
    sa.Column('script_hook', sa.Text(), nullable=True),
    sa.Column('script_body', sa.Text(), nullable=True),
    sa.Column('script_cta', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('music', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['tiktok_research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiktok_trend_results')
    op.drop_table('tiktok_research_projects')
    # ### end Alembic commands ###