"""init_db

Revision ID: da276690a0f2
Revises: 
Create Date: 2026-05-26 04:00:57.662770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da276690a0f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('main_topic', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiktok_research_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('full_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiktok_trend_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('views', sa.String(length=50), nullable=True),
    sa.Column('likes', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=50), nullable=True),
    sa.Column('engagement', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=100), nullable=True),
    sa.Column('script_hook', sa.Text(), nullable=True),
    sa.Column('script_body', sa.Text(), nullable=True),
    sa.Column('script_cta', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('music', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['tiktok_research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_channels',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('keyword_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_analyses',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('topic_summary', sa.Text(), nullable=True),
    sa.Column('viewer_insight', sa.Text(), nullable=True),
    sa.Column('title_analysis', sa.Text(), nullable=True),
    sa.Column('thumbnail_analysis', sa.Text(), nullable=True),
    sa.Column('reason_for_success', sa.Text(), nullable=True),
    sa.Column('remake_advice', sa.Text(), nullable=True),
    sa.Column('suggested_title', sa.Text(), nullable=True),
    sa.Column('suggested_thumbnail_text', sa.Text(), nullable=True),
    sa.Column('suggested_outline', sa.Text(), nullable=True),
    sa.Column('suggested_prompt', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('video_scores',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('title_score', sa.Float(), nullable=True),
    sa.Column('thumbnail_score', sa.Float(), nullable=True),
    sa.Column('remake_score', sa.Float(), nullable=True),
    sa.Column('production_difficulty', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('vph', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_scores')
    op.drop_table('ai_analyses')
    op.drop_table('youtube_videos')
    op.drop_table('youtube_channels')
    op.drop_table('tiktok_trend_results')
    op.drop_table('script_segments')
    op.drop_table('video_jobs')
    op.drop_table('tiktok_research_projects')
    op.drop_table('research_projects')
    # ### end Alembic commands ###